### ISSUE TITLE
Seems like lacking a script file(utils.py)

### ISSUE THREAD

**Issue by gsh150801** [Layne-Huang/CoaDTI#1]
When I ran 'python train.py', I got such error information:
  Traceback (most recent call last):
    File "train.py", line 22, in <module>
      from utilts import *
  ModuleNotFoundError: No module named 'utilts'
It seems that a script file named utils.py is lacking in code folder.

**Comment by Layne-Huang** [comment]
Thanks for your reminder.

I have uploaded utils.py to the repository.

Thank you for your attention.
